name: Add two numbers build and test
on:  
  workflow_dispatch:
    push:
      branches:
        - [ "main", "develop" ]
    pull_request:
      branches:
        - [ "main", "develop" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create build dir
        run: cmake -S. -Bbuild add_two_numbers/
      - name: build
        run: cmake --build build/
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: ctest --test-dir build/ -V