name: Two sum build and test
on:  
  workflow_dispatch:
    push:
      branches:
        - develop
    pull_request:
      branches:
        - develop
jobs:
 Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create build dir
        run: cmake -S. -Bbuild two_sum/
      - name: build
        run: cmake --build build/
      - name: test
        run: ctest --test-dir build/ -V