name: Two sum build and test
on:  
  workflow_dispatch:
    push:
      branches:
        - [ "main", "develop" ]
    pull_request:
      branches:
        - [ "main", "develop" ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt install libgtest-dev
      - uses: actions/checkout@v4
      - name: create build dir
        run: cmake -S. -Bbuild two_sum/
      - name: build
        run: cmake --build build/       
      - name: test
        run: ctest --test-dir build/ -V